image: golang:1.15.8

stages:
  - fuzz

include:
  - template: Coverage-Fuzzing.gitlab-ci.yml

my_fuzz_target:
  extends: .fuzz_base
  image: golang:1.15.8
  allow_failure: false
  variables:
    COVFUZZ_SEED_CORPUS: './xdr/fuzz/jsonclaimpredicate/corpus'
  script:
    - apt update && apt install -y clang
    - go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build
    - cd xdr/fuzz/jsonclaimpredicate
    - go-fuzz-build -libfuzzer -o my_fuzz_target.a .
    - clang -fsanitize=fuzzer my_fuzz_target.a -o ../../../my_fuzz_target
    - cd ../../../
    - timeout --preserve-status --signal=INT 300s ./gitlab-cov-fuzz run --regression=$REGRESSION -- ./my_fuzz_target || true
    - ls -l ./crashes/
    - echo "done"

# test MR widget
