package main

import (
	_ "embed"
	"fmt"
)

// Generator holds the type resolver and definition list for code generation.
type Generator struct {
	TypeResolver
	allDefs []DefWrap
}

// NewGenerator creates a generator from an IR.
func NewGenerator(ir *IR) (*Generator, error) {
	seen := make(map[string]bool, len(ir.Definitions))
	for _, d := range ir.Definitions {
		if seen[d.Name()] {
			return nil, fmt.Errorf("duplicate definition name %q in IR", d.Name())
		}
		seen[d.Name()] = true
	}

	return &Generator{
		TypeResolver: NewTypeResolver(ir),
		allDefs:      ir.Definitions,
	}, nil
}

//go:embed view_support.go.txt
var viewSupportCode string

func (g *Generator) GenerateViews() ([]byte, error) {
	// Phase 1: Plan — resolve all types, compute inline names.
	plan, err := g.PlanViews()
	if err != nil {
		return nil, err
	}

	// Phase 2: Emit — write Go source from the plan.
	f := NewGeneratedFile("xdr")
	f.Preamble("// Code generated by xdrgen. DO NOT EDIT.")
	f.AddImport("encoding/binary")
	f.AddImport("bytes")
	f.AddImport("fmt")
	f.AddImport("iter")
	f.AddImport("math")
	f.P(viewSupportCode)

	for _, entry := range plan.Entries {
		switch e := entry.(type) {
		case *InlineTypePlan:
			emitConcreteViewType(f, e.Name, e.ViewType)
		case *StructViewPlan:
			emitStructViewFromPlan(f, e)
		case *UnionViewPlan:
			emitUnionViewFromPlan(f, e)
		case *EnumViewPlan:
			emitEnumViewFromPlan(f, e)
		case *TypedefViewPlan:
			emitTypedefViewFromPlan(f, e)
		}
	}

	return f.Content()
}
