package main

import (
	"bytes"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
)

// valueAccessorRE matches a generated leaf Value() accessor whose return type is
// a single Go identifier — a named type (enum, flags, fixed-opaque typedef, or a
// sibling view type), or a builtin scalar (bool/int32/uint32/...). It is the
// in-process embodiment of the grep that previously regenerated the conformance
// harness's typedValueViewTypes list by hand. It deliberately does NOT match
// composite return types ([]byte, [N]byte), so variable/anonymous-opaque views
// are excluded — exactly as the old hand-grepped list excluded them.
//
// It runs over the fully generated views source (the embedded hand-written
// support file plus the plan-emitted types), so it captures the scalar views
// defined in view_support.go.txt as well as every plan-emitted enum, named
// fixed-opaque, and the handful of struct field accessors that happen to be
// named Value() — i.e. precisely the set the harness needs.
var valueAccessorRE = regexp.MustCompile(`(?m)^func \(v ([A-Za-z0-9]+View)\) Value\(\) \([A-Za-z0-9]+, error\)`)

// collectTypedValueViewTypes scans generated views source and returns, sorted,
// the names of every view type that exposes a typed Value() accessor returning a
// named Go type. The sort key is (lowercase, original) so the ordering is
// deterministic and machine-independent (it reproduces the locale-aware ordering
// of the previously hand-maintained list without depending on a locale).
func collectTypedValueViewTypes(viewsSource []byte) []string {
	seen := make(map[string]bool)
	var names []string
	for _, m := range valueAccessorRE.FindAllSubmatch(viewsSource, -1) {
		name := string(m[1])
		if seen[name] {
			continue
		}
		seen[name] = true
		names = append(names, name)
	}
	sort.Slice(names, func(i, j int) bool {
		li, lj := strings.ToLower(names[i]), strings.ToLower(names[j])
		if li != lj {
			return li < lj
		}
		return names[i] < names[j]
	})
	return names
}

// GenerateViewsRegistry emits the generated conformance-harness registry test
// file: package xdr_test, declaring typedValueViewTypes — every view type with a
// typed Value() accessor — derived from the generated views source so it stays in
// lockstep with the views and never needs manual regeneration. The viewsSource is
// the output of GenerateViews().
func GenerateViewsRegistry(viewsSource []byte) ([]byte, error) {
	names := collectTypedValueViewTypes(viewsSource)
	if len(names) == 0 {
		return nil, fmt.Errorf("registry: no typed Value() view accessors found in generated views")
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by xdrgen. DO NOT EDIT.\n")
	buf.WriteString("package xdr_test\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"reflect\"\n\n")
	buf.WriteString("\t\"github.com/stellar/go-stellar-sdk/xdr\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString("// typedValueViewTypes is every view type with a typed Value() accessor (enum\n")
	buf.WriteString("// leaf views, flag views, fixed-opaque views). The conformance harness\n")
	buf.WriteString("// (xdr_views_conformance_test.go) consumes it via viewTypeByName/enumLeafViewFor\n")
	buf.WriteString("// to construct a discriminant's standalone leaf view by name and drive its\n")
	buf.WriteString("// Value() against the oracle.\n")
	buf.WriteString("var typedValueViewTypes = []reflect.Type{\n")
	for _, name := range names {
		fmt.Fprintf(&buf, "\treflect.TypeOf(xdr.%s(nil)),\n", name)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("registry: gofmt: %w", err)
	}
	return formatted, nil
}
